name: automod

services:
  automod-backend:
    container_name: automod-backend
    build:
      dockerfile: ./apps/backend/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL="postgres://automod-postgres@postgres"
      - API_TOKEN="super-secret-key"

  automod-bot:
    container_name: automod-bot
    volumes:
      - ./:/app
    build:
      dockerfile: ./apps/automod/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - API_TOKEN="super-secret-key"

  automod-postgres:
    image: postgres:17.5-alpine
    container_name: automod-postgres
    restart: always
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/pgdata
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./var/storage/postgres_data
      o: bind
